name: publish

on:
  push:
    branches:
      - main
    paths:
      - '*/PKGBUILD'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Find updated package
        run: |
          #!/usr/bin/env bash
          set -euo pipefail

          pkgbuild="$(git diff --name-only HEAD~1 HEAD -- '*/PKGBUILD' '*/.SRCINFO' \
            | sed -E 's|/[^/]+$||' \
            | sort -u \
            | head -n1)"

          echo "pkgbuild=$pkgbuild" >> "$GITHUB_ENV"
          echo "Detected pkgbuild: $pkgbuild"

      - name: Publish package
        if: ${{ env.pkgbuild != '' }}
        uses: KSXGitHub/github-actions-deploy-aur@da03e160361ce01bf087e790b6ffd196d7dccff7 # v4.1.3
        with:
          pkgname: ${{ env.pkgbuild }}
          pkgbuild: ${{ env.pkgbuild }}/PKGBUILD
          assets: |
            ${{ env.pkgbuild }}/*
            ${{ env.pkgbuild }}/.[!.]*
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
